######################################################################
# Automatically generated by qmake (3.1) Tue Aug 18 16:10:06 2026
######################################################################

TEMPLATE = app
TARGET = Mani
INCLUDEPATH += .

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_UP_TO=0x060000 # disables all APIs deprecated in Qt 6.0.0 and earlier

# Input
HEADERS += src/MainWindow.h \
           src/database/Database.h \
           src/model/Cuenta.h \
           src/model/GastoCategoria.h \
           src/model/Moneda.h \
           src/model/Movimiento.h \
           src/model/ResumenMes.h \
           src/platform/TouchIdAuth.h \
           src/ui/BarChartWidget.h \
           src/ui/CuentaCardWidget.h \
           src/ui/CuentaDialog.h \
           src/ui/HistorialDialog.h \
           src/ui/LockDialog.h \
           src/ui/MovimientoDialog.h \
           src/ui/MovimientosCuentaDialog.h \
           src/ui/PasswordConfigDialog.h \
           src/ui/ReportesDialog.h \
           src/ui/TotalesPanelWidget.h \
           src/util/AppLock.h \
           src/util/AppPaths.h \
           src/util/CsvIO.h \
           src/util/MesActivo.h \
           src/util/Money.h \
           src/util/Totales.h
SOURCES += src/main.cpp \
           src/MainWindow.cpp \
           build/Mani_autogen/mocs_compilation.cpp \
           build-release/Mani_autogen/mocs_compilation.cpp \
           src/database/Database.cpp \
           src/platform/TouchIdAuth_stub.cpp \
           src/ui/BarChartWidget.cpp \
           src/ui/CuentaCardWidget.cpp \
           src/ui/CuentaDialog.cpp \
           src/ui/HistorialDialog.cpp \
           src/ui/LockDialog.cpp \
           src/ui/MovimientoDialog.cpp \
           src/ui/MovimientosCuentaDialog.cpp \
           src/ui/PasswordConfigDialog.cpp \
           src/ui/ReportesDialog.cpp \
           src/ui/TotalesPanelWidget.cpp \
           src/util/AppLock.cpp \
           src/util/AppPaths.cpp \
           src/util/CsvIO.cpp \
           src/util/MesActivo.cpp \
           src/util/Money.cpp \
           src/util/Totales.cpp \
           build/CMakeFiles/4.1.0/CompilerIdCXX/apple-sdk.cpp \
           build/CMakeFiles/4.1.0/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           build-release/CMakeFiles/4.1.0/CompilerIdCXX/apple-sdk.cpp \
           build-release/CMakeFiles/4.1.0/CompilerIdCXX/CMakeCXXCompilerId.cpp
TRANSLATIONS += build/CMakeFiles/Mani.dir/compiler_depend.ts \
                build/CMakeFiles/Mani_autogen.dir/compiler_depend.ts \
                build/CMakeFiles/Mani_autogen_timestamp_deps.dir/compiler_depend.ts \
                build-release/CMakeFiles/Mani.dir/compiler_depend.ts \
                build-release/CMakeFiles/Mani_autogen.dir/compiler_depend.ts \
                build-release/CMakeFiles/Mani_autogen_timestamp_deps.dir/compiler_depend.ts
